//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiFive {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class appSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static appSettings defaultInstance = ((appSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new appSettings())));
        
        public static appSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.2:82/")]
        public string serverUri {
            get {
                return ((string)(this["serverUri"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1 DAY (24 hours)")]
        public string dayPackageName {
            get {
                return ((string)(this["dayPackageName"]));
            }
            set {
                this["dayPackageName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1 WEEK (7 days)")]
        public string weekPackageName {
            get {
                return ((string)(this["weekPackageName"]));
            }
            set {
                this["weekPackageName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1 MONTH (30 days)")]
        public string monthPackageName {
            get {
                return ((string)(this["monthPackageName"]));
            }
            set {
                this["monthPackageName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("86400")]
        public string dayPackage {
            get {
                return ((string)(this["dayPackage"]));
            }
            set {
                this["dayPackage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("604800")]
        public string weekPackage {
            get {
                return ((string)(this["weekPackage"]));
            }
            set {
                this["weekPackage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2592000")]
        public string monthPackage {
            get {
                return ((string)(this["monthPackage"]));
            }
            set {
                this["monthPackage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("generateaccounts?number=1&pass=1JC8QBAQ037FNQL37JSBBSLP83EC60&type=2&sell=1&passl" +
            "ength=5&unlquota=1&download=10000&upload=10000&timeleft={0}&inactivity=0")]
        public string accountCall {
            get {
                return ((string)(this["accountCall"]));
            }
            set {
                this["accountCall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172800")]
        public string twoDayPackage {
            get {
                return ((string)(this["twoDayPackage"]));
            }
            set {
                this["twoDayPackage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("259200")]
        public string threeDayPackage {
            get {
                return ((string)(this["threeDayPackage"]));
            }
            set {
                this["threeDayPackage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2 DAYS (48 hours)")]
        public string twoDayPackageName {
            get {
                return ((string)(this["twoDayPackageName"]));
            }
            set {
                this["twoDayPackageName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3 DAYS (72 hours)")]
        public string threeDayPackageName {
            get {
                return ((string)(this["threeDayPackageName"]));
            }
            set {
                this["threeDayPackageName"] = value;
            }
        }
    }
}
